# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
  data_path: body_keypoints_full_test/X_test_processed.npy
  label_path: body_keypoints_full_test/y_test.npy
  laban_path: body_keypoints_full_test/X_test_laban.npy
  info_path: body_keypoints_full_test/info_test.npy
  debug: False

# model
model: model.msg3d_laban.Model
model_args:
  in_channels: 15
  num_class: 5
  num_point: 24
  layer_channels: 12
  num_person: 1
  num_gcn_scales: 13    # `num_scales` == `K + 1` in the paper
  num_g3d_scales: 6
  graph: graph.ntu_rgb_d.AdjMatrixGraph
personality_index: -1


# test
phase: test
device: [0]
test_batch_size: 16
weights: ./work_dir/personality/msg3d_joint/weights/weights-8-7424-best.pt
num_worker: 0
# weights-24-17664-best-my.pt

work_dir: ./eval/personality/joint/
save_score: True
